
version: '3.8'

services:
  app:
    image: backend3/werent:team3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: SaleMate
    ports:
      - '5000:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
