version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/mydatabase' # Update with your actual database credentials
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: SaleMate
    ports:
      - '5432:5000'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
